all:
	pdflatex  -synctex=1 -interaction=nonstopmode -file-line-error -recorder -output-directory="/media/d/git/nsysu/cs/report/presentation/0806"  "/media/d/git/nsysu/cs/report/presentation/0806/main.tex"
clean:
	rm -f `ls -p | grep -v "/\|main.tex\|main.pdf\|Makefile\|main.bib\|methFlow.pdf"`
