all:
	pdflatex  -synctex=1 -interaction=nonstopmode -file-line-error -recorder -output-directory="/media/d/git/nsysu/cs/report/presentation/0113"  "/media/d/git/nsysu/cs/report/presentation/0113/main.tex"
clean:
	rm -f `ls -p | grep -v "/\|main.tex\|main.pdf\|Makefile\|main.bib\|專題進度報告表.doc"`
