version: '3.9'
services: 
  swag:
    image: ghcr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Taipei
      - URL=lab.scc-net.tw
      - VALIDATION=http
    volumes:
      - /media/d/git/nsysu/cs/fhir/demo/victim/swag/config:/config
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped